### ISSUE TITLE
Would like to contribute to this repo. 

### ISSUE THREAD

**Issue by aniruddha-5** [WarriorWhoCodesCommunity/news-letter#1]
I can work on creating this newsletter, considering if I can get few more details about project.

**Comment by AnkushSinghGandhi** [comment]
In this repo, there really is nothing you can do. The newsletter is intended to connect essential and useful information with our members and subscribers. Newsletters provide us with direct access to our audience's inboxes, allowing us to offer interesting material, advertise, and so on. So I'll recommend you check back here later in the future till then check other repos. for contribution.
